import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    flex: 1,
    width: "100%",
    height: "100%",
    overflow: "hidden",
  },
  hamburgerMenu: {
    position: "absolute",
    top: 70,
    right: 20,
    zIndex: 1000,
    backgroundColor: "white",
    borderRadius: 4,
    padding: 10,
    elevation: 5,
    shadowColor: "black",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  hamburgerIcon: {
    fontSize: 34,
  },
  sideNav: {
    position: "absolute",
    top: 120,
    right: 25,
    width: 200,
    height: "98%",
    backgroundColor: "white",
    borderLeftWidth: 1,
    borderColor: "white",
    padding: 20,
    elevation: 5,
    zIndex: 1000,
  },
  navButton: {
    fontSize: 18,
    padding: 8,
    top: -70,
    right: 15,
    color: "black",
  },
  toggleContainer: {
    position: "absolute",
    bottom: 20,
    right: 20,
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 4,
    padding: 10,
    elevation: 5,
    shadowColor: "black",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  toggleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f0f0f0",
    padding: 10,
    borderRadius: 10,
    marginVertical: 5,
    width: "100%",
    top: -50,
    left: 15,
  },
  toggleSelectButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f0f0f0",
    padding: 12,
    borderRadius: 10,
    marginVertical: 5,
    width: "100%",
    top: -50,
    left: 15,
  },
  label: {
    fontSize: 14,
    color: "#333",
    textAlign: "center",
    marginHorizontal: 10,
    flex: 1,
  },
  switch: {
    transform: [{ scaleX: 1 }, { scaleY: 1 }],
  },
});
